# Generated by Django 4.2.1 on 2023-05-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=1000)),
                ('client_code', models.CharField(max_length=11)),
                ('pvm', models.CharField(max_length=20)),
            ],
        ),
    ]
