# Generated by Django 4.2.1 on 2023-05-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_is_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_code',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='client',
            name='pvm',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
