# Generated by Django 4.2.1 on 2023-05-23 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_end', models.DateField(blank=True)),
                ('car_model', models.CharField(blank=True, max_length=100)),
                ('car_comment', models.TextField(blank=True)),
                ('clients_str', models.CharField(max_length=100)),
                ('car_brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.brand')),
                ('client', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('consumptions', models.ManyToManyField(to='orders.consumption')),
            ],
        ),
    ]
