# Generated by Django 4.2.1 on 2023-05-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumption',
            name='is_actual',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_actual',
            field=models.BooleanField(default=True),
        ),
    ]
